joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01
  dev: /dev/input/js0

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /joy_teleop/cmd_vel
    axis_mappings:
      - axis: 1
        target: linear.x
        scale: 0.2
      - axis: 2
        target: angular.z
        scale: .34
  start_recording:
    type: service
    service_name: /recording
    service_request:
      status: True
    buttons: [2]
  stop_recording:
    type: service
    service_name: /recording
    service_request:
      status: False
    buttons: [1]