# USB port
serial_port: /dev/serial/by-path/platform-70090000.xusb-usb-0:2.3.3.2:1.0-port0
# Tf frame id
frame_id: imu_bosch_link
freqency: 50
use_temperature: true
use_magnetometer: true
operation_mode: IMU
reset_orientation: true
