# USB port
serial_port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
# Tf frame id
frame_id: imu_bosch_link
freqency: 50
use_temperature: true
use_magnetometer: true
operation_mode: IMU
reset_orientation: true
