version: "3.6"
services:
  slammer_drivers:
    privileged: true

    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - STARTUP_PACKAGE=slammer_driver
        - STARTUP_LAUNCH=driver.launch
    image: slammer_drivers
    network_mode: "host"
    volumes:
      - "../../..:/ros_melodic_robot/"
      - "/dev:/dev"


  slammer_description:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - STARTUP_PACKAGE=slammer_description
        - STARTUP_LAUNCH=description.launch
    image: slammer_description
    network_mode: "host"
    volumes:
      - "../../..:/ros_melodic_robot/"
    restart: on-failure
  slammer_control:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - STARTUP_PACKAGE=slammer_control
        - STARTUP_LAUNCH=control.launch
    image: slammer_control
    network_mode: "host"
    volumes:
      - "../../..:/ros_melodic_robot/"
      - "/dev:/dev"
    privileged: true

  slammer_teleop:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - STARTUP_PACKAGE=slammer_teleop
        - STARTUP_LAUNCH=teleop.launch
    image: slammer_teleop
    network_mode: "host"
    volumes:
      - "../../..:/ros_melodic_robot/"

  slammer_mapping:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - STARTUP_PACKAGE=slammer_mapping
        - STARTUP_LAUNCH=mapping.launch
    image: slammer_mapping
    network_mode: "host"
    volumes:
      - "../../..:/ros_melodic_robot/"

