version: "3.6"
services:
  drivers:
    extends: &extend
      file: docker-compose.base.yaml
      service: base
    build:
      args:
        - STARTUP_PACKAGE=slammer_driver
        - STARTUP_LAUNCH=driver.launch
    image: drivers

  description:
    extends: *extend
    build:
      args:
        - STARTUP_PACKAGE=slammer_description
        - STARTUP_LAUNCH=description.launch
    image: description

  teleop:
    extends: *extend
    build:
      args:
        - STARTUP_PACKAGE=slammer_teleop
        - STARTUP_LAUNCH=teleop.launch
    image: teleop

  control:
    extends: *extend
    build:
      args:
        - STARTUP_PACKAGE=slammer_control
        - STARTUP_LAUNCH=control.launch
    image: control
    depends_on:
      - description
      - teleop

  mapping:
    extends: *extend

    build:
      args:
        - STARTUP_PACKAGE=slammer_mapping
        - STARTUP_LAUNCH=mapping.launch
    image: mapping
    privileged: true
    depends_on: 
      - drivers
      - control

  navigation:
    extends: *extend

    build:
      args:
        - STARTUP_PACKAGE=slammer_navigation
        - STARTUP_LAUNCH=move_base.launch
    image: slammer_navigation
    depends_on: 
      - mapping
      - control
