version: "3.6"
services:
  base:
    privileged: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: drivers
    network_mode: "host"
    volumes:
      - "../../../.ccache:/root/ccache"
      - "../../../.docker_ws:/ros_melodic_robot/"
      - "../../../.docker_ws/.ros/:/root/.ros/"
      - "../../../src/:/ros_melodic_robot/src/"
      - "/dev:/dev"
    restart: on-failure
