joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['joint2']
  right_wheel: ['joint1']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  

  cmd_vel_timeout: 0.25
  base_frame_id: base_link

  k_l: 0.1
  k_r: 0.1

  estimate_velocity_from_position: false
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  wheel_radius:                 0.06
  wheel_separation:             0.24

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration: 1.0
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2
