obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.15, -0.10], [-0.15, 0.10], [0.15, 0.10], [0.15, -0.10]]
#robot_radius: ir_of_robot
inflation_radius: 0.30
footprint_padding: 0.1
robot_base_frame: base_link

observation_sources: [ laser_scan_sensor, point_cloud_sensor ]

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud, topic: /camera/depth/image_rect_raw, marking: true, clearing: true}