global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  rolling_window: true
  track_unknown_space: true

  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}