# USB port
port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
# Tf frame id
frame_id: imu_bosch_link
# Data reading frequency
freqency: 200
# Sensor operation mode --> modes could be found in sensor datasheet
operation_mode: 0x08
