world_frame: odom
odom_frame: odom
base_link_frame: base_link
two_d_mode: true
frequency: 50

# Sensor configuration http://docs.ros.org/melodic/api/robot_localization/html/state_estimation_nodes.html#sensor-config
#        X,         Y,        Z,
#     roll,     pitch,      yaw,
#    dot X,     dot Y,    dot Z,
# dot roll, dot pitch,  dot yaw,
# dotdot X,  dotdot Y, dotdot Z

################ wheels ODOM0 ################

odom0: /velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, false,
               false, false, false]
odom0_differential: false

################ visual ODOM1 ################

#odom1: /odometry/vis_odom
#odom1_config: [true, true, true,
#               false, false, false,
#               true, true, true,
#               false, false, false,
#               false, false, false]
#
#odom1_differential: false
#odom1_relative: true

################ IMU0 ################

imu0: /boschimu/imu/raw
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]

imu0_differential: false